# Docker Compose configuration for Othor AI

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DEBUG=True
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - UPLOAD_DIR=/app/data/uploads
      - MODEL_DIR=/app/data/models
      - MAX_FILE_SIZE=52428800
      - SESSION_TIMEOUT=86400
      # Database configuration (SQLite fallback for simplicity)
      - DATABASE_URL=sqlite:///./data/othor_ai.db
      # JWT configuration
      - SECRET_KEY=othor-ai-docker-secret-key-2024
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      # CORS configuration
      - ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://frontend:3000
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O- http://localhost:8001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - othor-ai-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001
      - NEXT_PUBLIC_API_TIMEOUT=30000
      - NEXT_PUBLIC_MAX_FILE_SIZE=52428800
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - othor-ai-network

  # Optional: Redis for background jobs (bonus feature)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - othor-ai-network
    profiles:
      - bonus

  # Optional: PostgreSQL for data persistence (bonus feature)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: othor_ai
      POSTGRES_USER: othor_user
      POSTGRES_PASSWORD: othor_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U othor_user -d othor_ai"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - othor-ai-network
    profiles:
      - bonus

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  othor-ai-network:
    driver: bridge
